# Generated by Django 6.0.4 on 2026-04-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
    ]
